### ISSUE TITLE
Page sur les bénéficiaires✨

### ISSUE THREAD

**Issue by adrianadauria** [AfricTivistes/charter-portal-issues#13]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/AfricTivistes/charter-portal-issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby.

### Pain

Bonjour tout le monde, j'espère que vous allez bien! Avec Andrew Songa, on est en train d'organiser un événement le 7 juin pour annoncer les premiers bénéficiaires du soutien financier AGA (les infos plus detaillées vont suivre). Entretemps, je voulais demander si c'est possible de créer une page sur la plateforme que l'on va dédier au bénéficiaires, pour y mettre des photos et des paragraphes de présentation. L'idéal serait qu'elle soit prête **d'ici la fin du mois** pour qu'on puisse la compléter avec les infos après l'événement. 

### Suggested Solution

Une page facilement accessible depuis le menu sur la home page. 

### Tasks

- [x] Proposition de design
- [x] Intégration design
- [x] Ajouter à l'interface admin

**Comment by dofbi** [comment]
Bonjour @adrianadauria 🎉 
Content de vous livre 👍🏾 

Voici une proposition de présentation pour les bénéficiaires, quand pensez-vous ❓ 

![Capture d’écran du 2022-05-04 08-44-19](https://user-images.githubusercontent.com/84446/166649377-02eb52ae-04da-4dcb-8398-59b8b1533cdd.png)

Quel type d'information en plus du
- Nom du bénéficiaire
- Nom du projet
- Description du projet
- du site du projet
- des liens sociaux
Faut-il rajouter ❓

**Comment by dofbi** [comment]
Netlify Preview Deployment Information
- Log URL: https://app.netlify.com/sites/charter-portal/deploys/62748bf89aac0306be99ffbe
- Preview URL: https://62748bf89aac0306be99ffbe--charter-portal.netlify.app

**Comment by dofbi** [comment]
Hello @adrianadauria BÉNÉFICIAIRES Done
![Capture d’écran du 2022-06-08 12-13-56](https://user-images.githubusercontent.com/84446/172613495-c58ae7dd-471b-41a9-81b1-6a47618f0a6b.png)
