### ISSUE TITLE
Update site pour lancement

### ISSUE THREAD

**Issue by dofbi** [AfricTivistes/charter-portal-issues#14]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/AfricTivistes/charter-portal-issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby.

### CC

Hi

:Due date
Mardi 10 

### Pain

Changement d'urgence

### Suggested Solution

voire taches

### Tasks

- [ ] Navigation
  - [ ] Aller directe vers des pages depuis le header 
  - [x] masquer FAQ
- [x] A propos
  - [x] Changer le texte
- [x] Masque WATCH VIDEO
- [x] Masque Faq
- [x] Masque Spaces for collaboration between
- [x] #15
  - [x] garder les trois
  - [x] Sous titre bloc en Majuscule
  - [x] changement de titre
  - [x] Et un lien vers une page de description
  - [x] icons update
- [x] Masque KEY FIGURES
- [x] Masque Call for consultation for the Charter Project Africa
- [x] TESTIMONIALS
  - [x] masque photo
- [x] Powered by Partnerships
  - [x] Ajouter les liens
- [x] Subscribe to the Newslettertte
  - [x] Typo erreur
  - [x] bouton changer en "Subscribe"
- [x] Funded by European Union
  - [x] enlever titre
- [x] Footter
  - [x] Ajoueter Logo EU
  - [x] Revoir la mise en page voir footer https://civictechfund.africa

**Comment by dofbi** [comment]
Bonjour @adrianadauria @cissengary 
Les modifications demandées on été déployer sur l'adresse, [charter.africa](https://charter.africa) vous pouvez rafraîchir pour voir les changements
Mais aussi visité l'espace [admin](https://charter.africa/admin) pour apporter des changements
Il reste une modification concernant la navigation qui sera intégrée au plus vite.
Cordialement,
